### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by LHuldin** [tihvis/ot-harjoitustyo#1]
Projekti kloonattu 30.4. klo 16.45.

- Sovellusta testatessani ei vastaan tullut minkäänlaisia ongelmia ja ohjelma toimi toivotulla tavalla ja mielestäni erittäin johdonmukaisesti. 

- Sovelluksen käyttöliittymä on mielestäni erittäin selkeä ja helppokäyttöinen.

- testit (55 kpl) testaavat laajasti vaadittuja osia sovelluksesta. Testien haarautumiskattavuuden ollessa samalla 98% on testaaminen erittäin hyvällä mallilla sovelluksessa.

- Pylint virheitä ei löydy, testauksen antaessa arvosanan 10.00 / 10 

- Koodi on jaettu erittäin hyvin kurssin ohjeiden mukaisesti. Käyttöliittymä on eriytetty hyvin muusta sovellus logiikasta samalla tietokantojen käytön ollessa myös eriytettynä omiin luokkiinsa.

- Sovelluksen koodi on kauttaaltaan ja mielestäni erittäin selkeästi kommentoitu kurssin mukaisella docstring tyylillä

- Tietokantoja myös käytetään laajasti osana sovellusta ja niiden käsittely on laadukasta.

- Sovellus on kaiken kaikkiaan hyvin valmiin oloinen laadukkaine ohjeineen, sen samalla täyttäessä lähes kaiken vaatimusmäärittelyn kattaman toiminnallisuuden. Mitään konkreettista parannus ehdotusta on mielestäni tässä vaiheessa vaikea antaa sovelluksen ollessa näin hyvällä mallilla.

**Comment by tihvis** [comment]
Kiitos kommenteista! 😎
